LibraryManagement.Web/LibraryManagement.Web/Controllers/BookController.cs
using LibraryManagement.Web.Models.Book;
using LibraryManagement.Web.Models.Category;
using LibraryManagement.Web.Models.Wiki;
using LibraryManagement.Web.Ultilities;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;

namespace LibraryManagement.Web.Controllers
{
    public class BookController : Controller
    {
        private readonly IWebHostEnvironment webHostEnvironment;

        public BookController(IWebHostEnvironment webHostEnvironment)
        {
            this.webHostEnvironment = webHostEnvironment;
        }
        [Route("book/index")]
        public IActionResult Index()
        {
            if (Request.Cookies["roleName"] == "System Admin" || Request.Cookies["roleName"] == "Thủ thư")
            {
                TempData["email"] = Request.Cookies["email"];
                TempData["avatar"] = Request.Cookies["avatar"];
                TempData["name"] = Request.Cookies["name"];
                TempData["role"] = Request.Cookies["roleName"];
                return View();
            }
            else
            {
                return View("~/Views/Home/AccessDenied.cshtml");
            }
        }
        [HttpGet]
        [Route("/book/gets")]
        public IActionResult Gets()
        {
            if (Request.Cookies["roleName"] == "System Admin" || Request.Cookies["roleName"] == "Thủ thư")
            {
                var books = ApiHelper<List<BookView>>.HttpGetAsync("book/gets");
                return Json(new { data = books });
            }
            else
            {
                return View("~/Views/Home/AccessDenied.cshtml");
            }
        }
        [HttpGet]
        [Route("/book/get/{id}")]
        public IActionResult Get(int id)
        {
            if (Request.Cookies["roleName"] == "System Admin" || Request.Cookies["roleName"] == "Thủ thư")
            {
                var books = ApiHelper<BookView>.HttpGetAsync(@$"book/get/{id}");
                return Json(new { data = books });
            }
            else
            {
                return View("~/Views/Home/AccessDenied.cshtml");
            }
        }
        [HttpGet]
        [Route("/book/status/gets")]
        public IActionResult GetStatus()
        {
            if (Request.Cookies["roleName"] == "System Admin" || Request.Cookies["roleName"] == "Thủ thư")
            {
                var status = ApiHelper<List<Status>>.HttpGetAsync($"wiki/status/{(int)Common.Table.Book},{false}");
                return Json(new { data = status });
            }
            else
            {
                return View("~/Views/Home/AccessDenied.cshtml");
            }
        }
        [HttpPost]
        [Route("/book/save")]
        public IActionResult Save([FromForm] SaveBookReq request)
        {
            if (Request.Cookies["roleName"] == "System Admin" || Request.Cookies["roleName"] == "Thủ thư")
            {
                var imagePathOld = request.ImagePath;
                if (request.Image != null)
                {
                    request.ImagePath = ProcessImagePath(request.Image);
                }
                request.CreatedBy = Request.Cookies["userId"];
                request.ModifiedBy = Request.Cookies["userId"];
                var result = ApiHelper<SaveBookRes>.HttpAsync($"book/save", "POST", request);
                if (result.Message == "Thao tác tạo mới sách thành công")
                {
                    CreateImg(request.Image, request.ImagePath);
                }
                if (result.Message == "Thao tác cập nhật sách thành công")
                {
                    EditImg(request.Image, request.ImagePath, imagePathOld);
                }
                return Json(new { data = result });
            }
            else
            {
                return View("~/Views/Home/AccessDenied.cshtml");
            }
        }
        [HttpPatch]
        [Route("/book/delete/{id}")]
        public IActionResult Delete(int id)
        {
            if (Request.Cookies["roleName"] == "System Admin" || Request.Cookies["roleName"] == "Thủ thư")
            {
                var request = new StatusBookReq()
                {
                    BookId = id,
                    StatusId = 4,
                    ModifiedBy = Request.Cookies["userId"]
                };
                var result = ApiHelper<SaveBookRes>.HttpAsync($"book/changeStatus", "PATCH", request);
                return Json(new { data = result });
            }
            else
            {
                return View("~/Views/Home/AccessDenied.cshtml");
            }
        }
        [HttpPatch]
        [Route("/book/changeStatusToOver/{id}")]
        public IActionResult ChangeStatusToOver(int id)
        {
            if (Request.Cookies["roleName"] == "System Admin" || Request.Cookies["roleName"] == "Thủ thư")
            {
                var request = new StatusBookReq()
                {
                    BookId = id,
                    StatusId = 2,
                    ModifiedBy = Request.Cookies["userId"]
                };
                var result = ApiHelper<SaveBookRes>.HttpAsync($"book/changeStatus", "PATCH", request);
                return Json(new { data = result });
            }
            else
            {
                return View("~/Views/Home/AccessDenied.cshtml");
            }
        }
        [HttpPatch]
        [Route("/book/changeStatusToStochking/{id}")]
        public IActionResult ChangeStatusToStochking(int id)
        {
            if (Request.Cookies["roleName"] == "System Admin" || Request.Cookies["roleName"] == "Thủ thư")
            {
                var request = new StatusBookReq()
                {
                    BookId = id,
                    StatusId = 1,
                    ModifiedBy = Request.Cookies["userId"]
                };
                var result = ApiHelper<SaveBookRes>.HttpAsync($"book/changeStatus", "PATCH", request);
                return Json(new { data = result });
            }
            else
            {
                return View("~/Views/Home/AccessDenied.cshtml");
            }
        }
        [HttpPatch]
        [Route("/book/changeStatusToPending/{id}")]
        public IActionResult ChangeStatusToPending(int id)
        {
            if (Request.Cookies["roleName"] == "System Admin" || Request.Cookies["roleName"] == "Thủ thư")
            {
                var request = new StatusBookReq()
                {
                    BookId = id,
                    StatusId = 3,
                    ModifiedBy = Request.Cookies["userId"]
                };
                var result = ApiHelper<SaveBookRes>.HttpAsync($"book/changeStatus", "PATCH", request);
                return Json(new { data = result });
            }
            else
            {
                return View("~/Views/Home/AccessDenied.cshtml");
            }
        }
        public string ProcessImagePath(IFormFile file)
        {
            string fileName = null;
            if (file != null)
            {
                fileName = $"{Guid.NewGuid()}_{file.FileName}";
            }
            return fileName;
        }

        [HttpGet]
        [Route("/book/topLoan")]
        public IActionResult TopLoan()
        {
            var books = ApiHelper<List<BookView>>.HttpGetAsync("book/topLoan");
            return Json(new { data = books });
        }
        [HttpGet]
        [Route("/book/topNew")]
        public IActionResult TopNew()
        {
            var books = ApiHelper<List<BookView>>.HttpGetAsync("book/topNew");
            return Json(new { data = books });
        }
        [HttpGet]
        [Route("/book/random")]
        public IActionResult Random()
        {
            var books = ApiHelper<List<BookView>>.HttpGetAsync("book/random");
            return Json(new { data = books });
        }
        [HttpGet]
        [Route("/book/getsCategory")]
        public IActionResult GetsCategory()
        {
            var categories = ApiHelper<List<CategoryView>>.HttpGetAsync("category/gets");
            return Json(new { data = categories });
        }
        public void CreateImg(IFormFile file, string fileName)
        {
            string uploadFolder = Path.Combine(webHostEnvironment.WebRootPath, "img");
            var filePath = Path.Combine(uploadFolder, fileName);
            using (var fs = new FileStream(filePath, FileMode.Create))
            {
                file.CopyTo(fs);
            }
        }
        public void EditImg(IFormFile file, string fileName, string fileNameOld)
        {
            if (file != null)
            {
                string uploadFolder = Path.Combine(webHostEnvironment.WebRootPath, "img");
                var filePath = Path.Combine(uploadFolder, fileName);
                using (var fs = new FileStream(filePath, FileMode.Create))
                {
                    file.CopyTo(fs);
                }
                if (!string.IsNullOrEmpty(fileNameOld) && (fileNameOld != "none-imgbook.png"))
                {
                    string delFile = Path.Combine(webHostEnvironment.WebRootPath
                                        , "img", fileNameOld);
                    System.IO.File.Delete(delFile);
                }
            }
        }
    }
}

LibraryManagement.Web/LibraryManagement.Web/Controllers/StudentController.cs
using LibraryManagement.Web.Models.Student;
using LibraryManagement.Web.Models.Wiki;
using LibraryManagement.Web.Ultilities;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;

namespace LibraryManagement.Web.Controllers
{
    public class StudentController : Controller
    {
        private readonly IWebHostEnvironment webHostEnvironment;

        public StudentController(IWebHostEnvironment webHostEnvironment)
        {
            this.webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            if (Request.Cookies["roleName"] == "System Admin" || Request.Cookies["roleName"] == "Thủ thư")
            {
                TempData["email"] = Request.Cookies["email"];
                TempData["avatar"] = Request.Cookies["avatar"];
                TempData["name"] = Request.Cookies["name"];
                TempData["role"] = Request.Cookies["roleName"];
                return View();
            }
            else
            {
                return View("~/Views/Home/AccessDenied.cshtml");
            }
        }
        [HttpGet]
        [Route("/student/gets")]
        public IActionResult Gets()
        {
            if (Request.Cookies["roleName"] == "System Admin" || Request.Cookies["roleName"] == "Thủ thư")
            {
                var students = ApiHelper<List<StudentView>>.HttpGetAsync("student/gets");
                return Json(new { data = students });
            }
            else
            {
                return View("~/Views/Home/AccessDenied.cshtml");
            }
        }
        [HttpGet]
        [Route("/student/get/{id}")]
        public IActionResult Get(int id)
        {
            if (Request.Cookies["roleName"] == "System Admin" || Request.Cookies["roleName"] == "Thủ thư")
            {
                var student = ApiHelper<StudentView>.HttpGetAsync(@$"student/get/{id}");
                return Json(new { data = student });
            }
            else
            {
                return View("~/Views/Home/AccessDenied.cshtml");
            }
        }
        [HttpGet]
        [Route("/student/status/gets")]
        public IActionResult GetStatus()
        {
            if (Request.Cookies["roleName"] == "System Admin" || Request.Cookies["roleName"] == "Thủ thư")
            {
                var status = ApiHelper<List<Status>>.HttpGetAsync($"wiki/status/{(int)Common.Table.Student},{false}");
                return Json(new { data = status });
            }
            else
            {
                return View("~/Views/Home/AccessDenied.cshtml");
            }
        }
        [HttpPost]
        [Route("/student/save")]
        public IActionResult Save([FromForm] SaveStudentReq request)
        {
            if (Request.Cookies["roleName"] == "System Admin" || Request.Cookies["roleName"] == "Thủ thư")
            {
                var avatarPathOld = request.AvatarPath;
                if (request.Avatar != null)
                {
                    request.AvatarPath = ProcessAvatarPath(request.Avatar);
                }
                request.CreatedBy = Request.Cookies["userId"];
                request.ModifiedBy = Request.Cookies["userId"];
                var result = ApiHelper<SaveStudentRes>.HttpAsync($"student/save", "POST", request);
                if (result.Message == "Thao tác tạo mới Student thành công" && request.AvatarPath != "none-avatar.png")
                {
                    CreateAvatar(request.Avatar, request.AvatarPath);
                }
                if (result.Message == "Thao tác cập nhật Student thành công")
                {
                    EditAvatar(request.Avatar, request.AvatarPath, avatarPathOld);
                }
                return Json(new { data = result });
            }
            else
            {
                return View("~/Views/Home/AccessDenied.cshtml");
            }
        }
        [HttpPatch]
        [Route("/student/delete/{id}")]
        public IActionResult Delete(int id)
        {
            if (Request.Cookies["roleName"] == "System Admin" || Request.Cookies["roleName"] == "Thủ thư")
            {
                var request = new StatusStudentReq()
                {
                    StudentId = id,
                    StatusId = 4,
                    ModifiedBy = Request.Cookies["userId"]
                };
                var result = ApiHelper<SaveStudentRes>.HttpAsync($"student/changeStatus", "PATCH", request);
                return Json(new { data = result });
            }
            else
            {
                return View("~/Views/Home/AccessDenied.cshtml");
            }
        }
        [HttpPatch]
        [Route("/student/changeStatusToBlocked/{id}")]
        public IActionResult ChangeStatusToBlocked(int id)
        {
            if (Request.Cookies["roleName"] == "System Admin" || Request.Cookies["roleName"] == "Thủ thư")
            {
                var request = new StatusStudentReq()
                {
                    StudentId = id,
                    StatusId = 3,
                    ModifiedBy = Request.Cookies["userId"]
                };
                var result = ApiHelper<SaveStudentRes>.HttpAsync($"student/changeStatus", "PATCH", request);
                return Json(new { data = result });
            }
            else
            {
                return View("~/Views/Home/AccessDenied.cshtml");
            }
        }
        [HttpPatch]
        [Route("/student/changeStatusToActive/{id}")]
        public IActionResult ChangeStatusToActive(int id)
        {
            if (Request.Cookies["roleName"] == "System Admin" || Request.Cookies["roleName"] == "Thủ thư")
            {
                var request = new StatusStudentReq()
                {
                    StudentId = id,
                    StatusId = 1,
                    ModifiedBy = Request.Cookies["userId"]
                };
                var result = ApiHelper<SaveStudentRes>.HttpAsync($"student/changeStatus", "PATCH", request);
                return Json(new { data = result });
            }
            else
            {
                return View("~/Views/Home/AccessDenied.cshtml");
            }
        }
        public string ProcessAvatarPath(IFormFile file)
        {
            string fileName = null;
            if (file != null)
            {
                fileName = $"{Guid.NewGuid()}_{file.FileName}";
            }
            return fileName;
        }
        public void CreateAvatar(IFormFile file, string fileName)
        {
            string uploadFolder = Path.Combine(webHostEnvironment.WebRootPath, "img");
            var filePath = Path.Combine(uploadFolder, fileName);
            using (var fs = new FileStream(filePath, FileMode.Create))
            {
                file.CopyTo(fs);
            }
        }
        public void EditAvatar(IFormFile file, string fileName, string fileNameOld)
        {
            if (file != null)
            {
                string uploadFolder = Path.Combine(webHostEnvironment.WebRootPath, "img");
                var filePath = Path.Combine(uploadFolder, fileName);
                using (var fs = new FileStream(filePath, FileMode.Create))
                {
                    file.CopyTo(fs);
                }
                if (!string.IsNullOrEmpty(fileNameOld) && (fileNameOld != "none-avatar.png"))
                {
                    string delFile = Path.Combine(webHostEnvironment.WebRootPath
                                        , "img", fileNameOld);
                    System.IO.File.Delete(delFile);
                }
            }
        }
    }
}

LibraryManagement.Web/LibraryManagement.Web/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"]</title>
    <link href="~/Assets/startbootstrap-sb-admin-gh-pages/dist/css/styles.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/datatables/css/jquery.dataTables.min.css" rel="stylesheet" />
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Library</a>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">Trang chủ</a>
        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    @if (TempData["email"] != null)
                    {
                        <div class="text-center">
                            <p>@TempData["email"]</p>
                            <img src="/img/@TempData["avatar"]" style="width: 75px;" />
                            <p>@TempData["name"]</p>
                        </div>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item text-warning" href="javascript:;" onclick="layoutAdmin.logOut()">Đăng xuất</a>
                    }
                    else
                    {
                        <p class="text-danger text-center">Empty</p>
                    }
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Quản lý sách
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div id="collapseLayouts" aria-labelledby="headingOne" data-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" asp-controller="Category" asp-action="Index">Thể loại</a>
                                <a class="nav-link" asp-controller="Book" asp-action="Index">Sách</a>
                                <a class="nav-link" asp-controller="BookArchive" asp-action="Index">Kho sách</a>
                            </nav>
                        </div>
                        <a class="nav-link" asp-controller="LoanCard" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-bookmark"></i></div>
                            Thẻ mượn
                        </a>
                        <a class="nav-link" asp-controller="Student" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-graduation-cap"></i></div>
                            Danh sách học sinh
                        </a>
                        @if (TempData["role"] as string == "System Admin")
                        {
                            <a class="nav-link" asp-controller="User" asp-action="Index">
                                <div class="sb-nav-link-icon"><i class="fa fa-id-card"></i></div>
                                Quản lý tài khoản
                            </a>
                        }
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <section class="content">
                    <div class="container-fluid">
                        @RenderBody()
                    </div>
                </section>
                <!-- The Modal -->
                <div class="modal" id="detailsData">
                    <div class="modal-dialog modal-xl">
                        <div class="modal-content">

                            <!-- Modal Header -->
                            <div class="modal-header">
                                <h4 class="modal-title text-warning" id="dataModalTitle"></h4>
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                            </div>

                            <!-- Modal body -->
                            <div class="modal-body" id="dataModal">
                            </div>

                            <!-- Modal footer -->
                            <div class="modal-footer">
                                <button type="button" class="btn btn-danger" data-dismiss="modal">Đóng</button>
                            </div>

                        </div>
                    </div>
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2020</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/lib/bootbox.js/bootbox.min.js"></script>
    <script src="~/js/layoutAdmin.js" asp-append-version="true"></script>
    <script src="~/Assets/startbootstrap-sb-admin-gh-pages/dist/js/scripts.js"></script>
    <script src="~/Assets/startbootstrap-sb-admin-gh-pages/dist/assets/demo/datatables-demo.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>